# Generated by Django 6.1.2 on 2026-10-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
