# Generated by Django 6.1.2 on 2026-10-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='location',
            field=models.CharField(choices=[('local', 'Локально (файл на ПК)'), ('streaming', 'Стриминг (по ссылке)')], default='local', max_length=10),
        ),
        migrations.AddField(
            model_name='entry',
            name='streaming_url',
            field=models.URLField(blank=True),
        ),
    ]
