# Generated by Django 6.1.2 on 2026-10-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_title_imdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='tmdb_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='title',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
