# Generated by Django 6.1.2 on 2026-10-07 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_title_imdb_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='local_file',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='title',
            name='original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='title',
            name='tmdb_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='title',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LibraryFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'path')},
            },
        ),
    ]
