# Generated by Django 6.1.2 on 2026-10-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_entry_location_entry_streaming_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='streaming_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('entry', 'season', 'number')},
        ),
    ]
