# Generated by Django 6.1.2 on 2026-10-07 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_title_local_file_title_original_name_title_tmdb_type_and_more'),
        ('tracker', '0003_title_tmdb_type_alter_title_tmdb_id'),
    ]

    operations = [
    ]
