# Generated by Django 6.1.2 on 2026-10-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_merge_20261007_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='imdb_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='kp_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='metacritic_rating',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='title',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='title',
            name='rt_rating',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='title',
            name='tmdb_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
