# Generated by Django 6.1.2 on 2026-10-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_title_total_episodes_watchsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='local_file',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
